index.js, messages.js, scripts/utils/reply-text.js, scripts/v0.js, scripts/v1.js
- Refactor script to remove callback hell. Closes #1
- Update script dialog to pt-br. Closes #2
- Enable option to swap between v1 and v2 from scripts. Closes #6
=> Refactor BETA

.babelrc, index.js, package.json, yarn.lock
- Add support to the latest ES syntax #14
=> Feature add support to es8 syntax

.gitignore, index.js, package.json, public/login/index.css, routes/index.js, routes/login.js, routes/mass-message.js, routes/middlewares/index.js, routes/middlewares/is-authenticated.js, views/index.pug, views/layout/index.pug, views/login/index.pug, views/mass-message/index.pug, yarn.lock
- Feature login #18
- Access the `/login` route
- The login page should be rendered like screenshot below on desktop and mobile:
| desktop | mobile |
|---|---|
| <img width="1674" alt="screen shot 2017-07-11 at 13 45 31" src="https://user-images.githubusercontent.com/5435389/28079563-45d6378c-663f-11e7-8877-2a768d25b37e.png"> | <img width="397" alt="screen shot 2017-07-11 at 13 48 00" src="https://user-images.githubusercontent.com/5435389/28079693-c0425ee2-663f-11e7-8980-ecf1162ad991.png"> |
- Validate the validations
- Insert an invalid format of email
- Try to submit the form with empty fields
- If passes on the form validation, it should redirect to the `/mass-message` route
- Otherwise, redirect to the `/login` route again with last inputed data
=> Feature login

.drone.yml, Dockerfile, Procfile
=> Continous Integration setup

scripts/v0.js
- Update share url to be customized #3
=> Feature custom share URL

.env.example, bot/events/error.js, bot/events/message.js, bot/events/postback.js, bot/factory.js, bot/helpers/receive.js, scripts/v0.js
- Improvements Prerelease v1.0.0 #28
=> Feature improvements prerelease v1.0.0

CHANGELOG.md, bot/speeches/messages.js, package.json
Meninos, estou criando aqui uma nova leva de intenções para a Beta! Favor incorporar as soon as possible. 👍
=> New batch of intentions for Beta

bot/speeches/messages.js
Adicionamos duas novas interações, uma com QR e outra com imagem.
=> Teste de adição do Quick-Reply e da imagem

CHANGELOG.md, bot/speeches/v1/speech.js, package.json
Se não estiver entendendo nada, me liga.
=> Inserção de script "clone" para filtrar usuários que chegam via mensagem em massa

bot/speeches/messages.js, package.json
- Inserção nova interação | ideologia de gênero #67
=> Release v1.3.2

bot/speeches/messages.js
Nova intenção | Sem pressão
Muita gente tá respondendo a msg em massa da betinha só agora, mas o script já tá fora do ar pq a votação passou. Tô adicionando uma resposta para quando a pessoa mandar 'quero pressionar' :)
=> Release v1.3.4

bot/speeches/messages.js
Novas intenções pra Beta ficar mais esperta :) Sem pressa pra implementar!
=> Novas Intenções e Atualizações

bot/speeches/messages.js
Oi, queridos! Vocês acham que conseguimos implementar essa inserção hoje? Para aproveitar que amanhã é Dia Internacional da Não Violência Contra a Mulher :)
=> Inserção de intenção | violência contra mulher

bot/speeches/messages.js
Adicionei a intenção para quem quer agir pela PEC 181 sem precisar excluir a conversa e começar de novo! Não sei se fiz certo com os QR, mas como não tem nada vermelho além das chaves, acho que foi hehe
=> "Agir pela PEC 181" com QR  (até terça 9h)

bot/speeches/messages.js
Enviar uma das mensagens abaixo:
- quero enviar email
- quero pressionar
- o que fazer
- como enviar um email pros deputados
- quero enviar um email 
- como faço para perssionar?
- quero entrar em ação
- quero agir agora
- quero pressionar contra a PEC 181
- como faço pra enviar email?
- quero pressionar
O bot deverá responder com a chave `ASK_ACT_PEC181` pela IA com a mensagem:
```
Sabia que podia contar com você! Para ver a mensagem que vamos enviar aos deputados e deputadas que vão votar a PEC 181, clique no botão abaixo. Não se assuste com a linguagem, tive que traduzir pro Politiquês, que é a língua que eles entendem 🙄:
```
e os quick replies:
- `Enviar já`
- `Ver mensagem`
=> Hotfix PEC 181 QR message

bot/speeches/messages.js
Change text
`Prezados(as) membros da Comissão Especial da PEC 181/15, não podemos permitir que uma proposta que originalmente amplia os direitos das mulheres seja revertida em um cruel Cavalo de Troia, acabando com o direito de aborto já autorizado por Lei. Tampouco podemos limitar para 240 dias a licença maternidade para mães de bebês prematuros.Por isso, peço que V.Sa aprove os destaques propostos pelas bancadas,de modo que a PEC siga em tramitação respeitando os direitos das mulheres.Conto com vossa cooperação para impedir este retrocesso,reconhecendo a obrigação do Congresso em garantir e estender os direitos de todas e todos no Brasil.`
to
`Prezados(as) membros da Comissão Especial da PEC 181/15, não podemos permitir que uma proposta que originalmente amplia os direitos das mulheres …
=> Update text message on V1_QUICK_REPLY_H action

bot/speeches/messages.js
Oi, queridos! Conseguimos essa intenções até 2a de manhã?
=> Novas Intenções | 3 sobre assédio

bot/speeches/messages.js
Oi, queridos! Como essa semana é dia internacional da mulher, teremos mais movimentação na Beta. Vocês conseguiriam atualizar essas intenções até amanhã de manhã - ou se possível hoje no final do dia? Amanhã de manhã também vamos subir mais duas - só não coloco agora porque elas tem links de parceiros que ainda não foram postados. Obrigada!
=> Novas Intençôes | 8 de março

bot/speeches/messages.js
Pessoal, conseguimos atualizar hoje?
=> Marielle (#109)

CHANGELOG.md, bot/speeches/messages.js, package-lock.json, package.json
Atualizando mensagens importantes pra esse momento de pressão :)
=> Atualizando intenções

bot/speeches/messages.js
Fizemos um mutirão aqui pra atualizar uma série de intenções da Beta! Pra afiar os algoritmos pra quando o script novo for ao ar ;)
=> Atualização Geral

bot/speeches/messages.js
Camila, essas intenções são sobre a pauta que adiantou no Congresso! Vou testar em staging pra já te avisar se for certinho
=> Intenções sobre o Radar Feminista

bot/speeches/messages.js
* Intenções sobre o Radar Feminista
Camila, essas intenções são sobre a pauta que adiantou no Congresso! Vou testar em staging pra já te avisar se for certinho
* Update messages.js
* Radar Feminista | atualização 2
Camila, precisei fazer uma mudança numa das respostas!
=> Intenções sobre o Radar Feminista (#144)

graphql/mutations/create-facebook-bot-campaign.js, graphql/mutations/update-facebook-bot-campaign-activists.js
* fix(graphql): Fix typo in query facebook create campaign
* fix(graphql): Fix typo in query facebook update campaign activists
=> fix(graphql): Fix typo in query facebook create campaign (#200)

bot/speeches/messages.js
* Nova intenção | eleições
* Update messages.js
=> Nova intenção | eleições (#217)

bot/speeches/button-texts.js, bot/speeches/carousel-texts.js, bot/speeches/messages.js, bot/speeches/v2/speech.js
* feat(script): update ADPF442 script
* feat(script): update ADPF442 card images
* feat(script): update ADPF442 script text
=> Feature/adpf new script (#221)

bot/speeches/messages.js
Novas intencoes pec 29 e ABOUT_PL_1256
=> Pec 29 (#248)

src/playground/actions.js, src/playground/factory.js
- Configure persistent menu from `Bonde/Chatbot` module.
- Restarting Express Routing also when by changing `chatbot.updated_at`.
- https://github.com/nossas/bonde-migrations/pull/9
- https://github.com/nossas/bonde-install/pull/31
=> Feature Persistent Menu

package.json, src/playground/actions.js, src/playground/events.js, src/playground/factory.js, src/playground/helpers.ts, src/playground/interactions.ts, src/playground/speech.js, src/playground/strategy.ts, yarn.lock
**depends on:**
https://github.com/nossas/bonde-migrations/pull/23
- Refatorado a parte de contexto, agora é possível acessar a última interação do bot para validar fluxos alternativos
- Implementado modelo de Ação criado no `bonde-diagram`, uma mensagem que aguarda uma opção de input do usuário, realiza uma validação nesse input e segue o fluxo de sucesso ou falha.
- Correção de alguns bugs de parse e ordenação
=> Feature Chatbot Action Context

src/playground/actions.js, src/playground/graphql.ts, src/playground/strategy.ts
depends_on:
- https://github.com/nossas/bonde-install/pull/37
- https://github.com/nossas/bonde-migrations/pull/24
=> feat: add pressure action
